models.py
from __init__ import db
from sqlalchemy.sql import func
from flask import Blueprint

models = Blueprint('models', __name__)

class vehicle_group(db.Model):
    vehicle_groupid = db.Column(db.Integer, primary_key=True)
    vehicle_groupdescription = db.Column(db.String(10000))
    vehicle_groupstatus = db.Column(db.String(10000))

class vehicle(db.Model):
    vehicleid = db.Column(db.Integer, primary_key=True)
    vehicledescription = db.Column(db.String(10000))
    vehicle_group = db.Column(db.String(10000))
    vehiclestatus = db.Column(db.String(10000))
    

__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager

db = SQLAlchemy()
DB_NAME = "vehicle.db"

def create_app():
    
    appNEW = Flask(__name__)
    appNEW.config['SECRET_KEY'] = 'hjshjhdjah kjshkjdhjs'
    appNEW.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(appNEW)
    
    from views import views
    from models import models
    
    appNEW.register_blueprint(views, url_prefix='/')
    appNEW.register_blueprint(models,url_prefix='/')

    create_database(appNEW)
    
    return appNEW

vehicles = []


def create_database(appNEW):
    if not path.exists('website/' + DB_NAME):
        db.create_all(app=appNEW)
        print('Created Database!')
        



    


    

main.py
from __init__ import create_app

appNEW = create_app()

if __name__ == '__main__':
    appNEW.run(debug=True)

views.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from models import vehicle, vehicle_group
from __init__ import db


views = Blueprint('views', __name__)


#main route for the vehicle form
@views.route('/')
def indexvehicle():
    vehiclesdata = vehicle.query.all()
    vehiclesgroupdata = vehicle_group.query.all()
    return render_template("vehicle.html", vehicles = vehiclesdata, vehiclesgroup = vehiclesgroupdata)


#main route for the vehicle_group form
@views.route('/vehicle_groupselect')
def indexgroup():
    vehiclegroupdata = vehicle_group.query.all()
    return render_template("vehicle_group.html",vehicles_group = vehiclegroupdata)
    
    
#main route for the about form
@views.route('/about')
def about():
    return render_template('about.html')

 
#this is our update route where we are going to add a vehicle
@views.route("/insert",methods=['POST'])
def insert():
    if request.method == 'POST':
        vehicleid = request.form.get('vehicleid')
        vehicledescription = request.form.get('vehicledescription')
        vehicle_group = request.form.get('vehicle_group')
        vehiclestatus = request.form.get('vehiclestatus')
        newDescription = vehicle(vehicleid = vehicleid, vehicle_group = vehicle_group, vehicledescription=vehicledescription, vehiclestatus = vehiclestatus)
        db.session.add(newDescription)
        db.session.commit()
        flash('Vehicle created!',category='success')
    return redirect(url_for('views.indexvehicle'))


#this is our update route where we are going to update our vehicle
@views.route('/update', methods = ['GET', 'POST'])
def update():
 
    if request.method == 'POST':
        my_data = vehicle.query.get(request.form.get('vehicleid'))
 
        my_data.vehicleid = request.form['vehicleid']
        my_data.vehicledescription = request.form['vehicledescription']
        my_data.vehicle_group = request.form['vehicle_group']
        my_data.vehiclestatus = request.form['vehiclestatus']
 
        db.session.commit()
        flash("Vehicle updated successfully")
 
        return redirect(url_for('views.indexvehicle'))
    
  
#This route is for deleting our vehicle
@views.route('/delete/<vehicleid>/', methods = ['GET', 'POST'])
def delete(vehicleid):
    my_data = vehicle.query.get(vehicleid)
    db.session.delete(my_data)
    db.session.commit()
    flash("Vehicle Deleted Successfully")
 
    return redirect(url_for('views.indexvehicle'))


#This route is for deleting our vehicle_group
@views.route('/deletegroup/<vehicle_groupid>/', methods = ['GET', 'POST'])
def deletegroup(vehicle_groupid):
    my_data = vehicle_group.query.get(vehicle_groupid)
    db.session.delete(my_data)
    db.session.commit()
    flash("Vehicle Deleted Successfully")
 
    return redirect(url_for('views.indexgroup'))


#this is our update route where we are going to add a vehicle_group
@views.route("/insertgroup",methods=['POST'])
def insertgroup():
    if request.method == 'POST':
        vehicle_groupid = request.form.get('vehicle_groupid')
        vehicle_groupdescription = request.form.get('vehicle_groupdescription')
        vehicle_groupstatus = request.form.get('vehicle_groupstatus')
        newgroupDescription = vehicle_group(vehicle_groupid = vehicle_groupid, vehicle_groupdescription = vehicle_groupdescription, vehicle_groupstatus=vehicle_groupstatus)
        db.session.add(newgroupDescription)
        db.session.commit()
        flash('Vehicle group created!',category='success')
    return redirect(url_for('views.indexgroup')) 


#this is our update route where we are going to update our vehicle_group
@views.route('/updategroup', methods = ['GET', 'POST'])
def updategroup():
 
    if request.method == 'POST':
        my_groupdata = vehicle_group.query.get(request.form.get('vehicle_groupid'))
 
        my_groupdata.vehicle_groupid = request.form['vehicle_groupid']
        my_groupdata.vehicle_groupdescription = request.form['vehicle_groupdescription']
        my_groupdata.vehicle_groupstatus = request.form['vehicle_groupstatus']
      
 
        db.session.commit()
        flash("Group Updated Successfully")
 
        return redirect(url_for('views.indexgroup'))

templates/about.html
{% include 'header.html' %}


{% block title %} <br>  <style> h1 {text-align: center} </style> <body> <h1>About: this website is created by Wouter</h1></body>  {% endblock %}

templates/header.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Vehicle registration</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</head>
<body>

<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Vehicle registration</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#collapsibleNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="collapsibleNavbar">
      <ul class="navbar-nav">
   

       
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">Master data</a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="/">Vehicle</a></li>
            <li><a class="dropdown-item" href="/vehicle_groupselect">Vehicle Group</a></li>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown">Other</a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="/about">About</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>



</body>
</html>

templates/vehicle.html
{% include 'header.html' %}

 
 
 
{% block title %}  {% endblock %}
<head> 
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
 
   <meta charset="UTF-8">
</head>
 
 
{% block body %}
 
<div class="container">
    <div class="row">
        <div class="col md-12">
 
            <div class="jumbotron p-3">
 
                <h2>Manage <b>vehicle </b>  <button type="button"  class="btn btn-success float-right"
                data-toggle="modal" data-target="#mymodal">Add new vehicle</button> </h2>

                
 
 
                {% with messages = get_flashed_messages() %}
 
                {% if messages %}
 
                {% for message in messages %}
 
                <div class="alert alert-success alert-dismissable" role="alert">
 
                    <button type="button" class="close" data-dismiss="alert" aria-label="close">
 
                        <span aria-hidden="true">x</span>
 
                    </button>
 
 
                {{message}}
 
 
                </div>
 
 
                {% endfor %}
 
                {% endif %}
                {% endwith %}
 
 
                <table class="table table-hover table-dark">
 
                    <tr>
 
                        <th>ID</th>
                        <th>Description</th>
                        <th>Group</th>
                        <th>Status</th>
                        <th>Action</th>
 
                    </tr>
 
 
                   {% for row in vehicles %}
                    <tr>
                        <td>{{row.vehicleid}}</td>
                        <td>{{row.vehicledescription}}</td>
                        <td>{{row.vehicle_group}}</td>
                        <td>{{row.vehiclestatus}}</td>
 
                        <td>
                            <a href="/update/{{row.vehicleid}}" class="btn btn-warning btn-xs" data-toggle="modal" data-target="#modaledit{{row.vehicleID}}">Edit</a>
                            <a href="/delete/{{row.vehicleid}}" class="btn btn-danger btn-xs" onclick="return confirm('Are You Sure To Delete ?')">Delete</a>
 
 
                        </td>
 
                    </tr>
 
 
                  <!-- Modal Edit Employee-->
<div id="modaledit{{row.vehicleID}}" class="modal fade" role="dialog">
   <div class="modal-dialog">
 
 
      <div class="modal-content">
 
 
         <div class="modal-header">
 
 
            <h4 class="modal-title">Update Information</h4>
 
 
         </div>
 
 
         <div class="modal-body">
 
 
            <form action="{{url_for('views.update')}}" method="POST">
 
 
               <div class="form-group">
 
 
                  <label>Description:</label>
                   <input type="hidden"  name="vehicleid" value="{{row.vehicleid}}">
 
                  <input type="text" class="form-control" name="vehicledescription" value="{{row.vehicledescription}}">
 
 
               </div>
 
 
 
               <div class="form-group">
                  <label>Group:</label>
                  <div class="input-group">
                          <select name="vehicle_group" class="selectpicker form-control">
                            {% for row in vehiclesgroup %}
                            <option value="{{ row.vehicle_groupdescription }}">{{ row.vehicle_groupdescription }}</option>
                            {% endfor %}
                          </select>
                  </div>
                </div>
 
 
               <div class="form-group">
 
 
                  
                
                  <label for="vehiclestatus" class="form-label">Status:</label>
                  <select class="form-select" id="vehiclestatus" name="vehiclestatus" required="1">
                    <option>Active</option>
                    <option>Inactive</option>

                  </select>
 
 
               </div>
 
 
               <div class="form-group">
 
 
                  <button class="btn btn-primary" type="submit">Update</button>
 
 
               </div>
 
 
            </form>
 
 
         </div>
 
 
         <div class="modal-footer">
 
 
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
 
 
         </div>
 
 
      </div>
 
 
   </div>
 
</div>
 
 
                    {% endfor %}
 
 
                </table>
 
 
            </div>
 
 
 
                  <!-- Modal Add Employee-->
 
 
<div id="mymodal" class="modal fade" role="dialog">
   <div class="modal-dialog">
      <div class="modal-content">
         <div class="modal-header">
 
            <h4 class="modal-title">Add Vehicle</h4>
         </div>
         <div class="modal-body">
 
            <form action="{{url_for('views.insert')}}" method="POST">
 
 
               <div class="form-group">
 
                  <label>Description:</label>
                  <input type="text" class="form-control" name="vehicledescription" required="1">
 
 
               </div>
 
 

               <div class="form-group">
                  <label>Group:</label>
                  <div class="input-group">
                          <select name="vehicle_group" class="selectpicker form-control">
                            {% for row in vehiclesgroup %}
                            <option value="{{ row.vehicle_groupdescription }}">{{ row.vehicle_groupdescription }}</option>
                            {% endfor %}
                          </select>
                  </div>
                </div>
 
 
                <div class="form-group">
 
 
                  
                
                  <label for="vehiclestatus" class="form-label">Status:</label>
                  <select class="form-select" id="vehiclestatus" name="vehiclestatus" required="1">
                    <option>Active</option>
                    <option>Inactive</option>

                  </select>
 
 
               </div>
 
 
 
               <div class="form-group">
 
 
                  <button class="btn btn-primary" type="submit">Add Vehicle</button>
 
 
               </div>
 
 
            </form>
 
 
         </div>
 
 
         <div class="modal-footer">
 
 
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
 
 
         </div>
 
 
      </div>
 
 
   </div>
 
 
</div>
 
 
 
 
 
        </div>
 
    </div>
 
 
</div>


 
 
{% endblock %}

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
 

templates/vehicle_group.html
{% include 'header.html' %}

 
 
 
{% block title %}  {% endblock %}
<head> 
   <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
 
   <meta charset="UTF-8">
</head>
 
 
{% block body %}
 
<div class="container">
    <div class="row">
        <div class="col md-12">
 
            <div class="jumbotron p-3">
 
                <h2>Manage <b>vehicle group </b>  <button type="button"  class="btn btn-success float-right"
                data-toggle="modal" data-target="#mymodal">Add new vehicle group</button> </h2>

                
 
 
                {% with messages = get_flashed_messages() %}
 
                {% if messages %}
 
                {% for message in messages %}
 
                <div class="alert alert-success alert-dismissable" role="alert">
 
                    <button type="button" class="close" data-dismiss="alert" aria-label="close">
 
                        <span aria-hidden="true">x</span>
 
                    </button>
 
 
                {{message}}
 
 
                </div>
 
 
                {% endfor %}
 
                {% endif %}
                {% endwith %}
 
 
                <table class="table table-hover table-dark">
 
                    <tr>
 
                        <th>ID</th>
                        <th>Description</th>
                        <th>status</th>
                        <th>Action</th>
 
                    </tr>
 
 
                   {% for row in vehicles_group %}
                    <tr>
                        <td>{{row.vehicle_groupid}}</td>
                        <td>{{row.vehicle_groupdescription}}</td>
                        <td>{{row.vehicle_groupstatus}}</td>
                       
 
                        <td>
                            <a href="/update/{{row.vehicle_groupid}}" class="btn btn-warning btn-xs" data-toggle="modal" data-target="#modaledit{{row.vehicle_groupid}}">Edit</a>
                            <a href="/deletegroup/{{row.vehicle_groupid}}" class="btn btn-danger btn-xs" onclick="return confirm('Are You Sure To Delete ?')">Delete</a>
 
 
                        </td>
 
                    </tr>
 
 
                  <!-- Modal Edit Employee-->
<div id="modaledit{{row.vehicle_groupid}}" class="modal fade" role="dialog">
   <div class="modal-dialog">
 
 
      <div class="modal-content">
 
 
         <div class="modal-header">
 
 
            <h4 class="modal-title">Update Information</h4>
 
 
         </div>
 
 
         <div class="modal-body">
 
 
            <form action="{{url_for('views.updategroup')}}" method="POST">
 
 
               <div class="form-group">
 
 
                  <label>Description:</label>
                   <input type="hidden"  name="vehicle_groupid" value="{{row.vehicle_groupid}}">
 
                  <input type="text" class="form-control" name="vehicle_groupdescription" value="{{row.vehicle_groupdescription}}">
 
 
               </div>
 
 
 
               <div class="form-group">
 
 
                  
                
                  <label for="vehicle_groupstatus" class="form-label">Status:</label>
                  <select class="form-select" id="vehicle_groupstatus" name="vehicle_groupstatus" required="1">
                    <option>Active</option>
                    <option>Inactive</option>

                  </select>
 
 
               </div>
 
 
 
 
               <div class="form-group">
 
 
                  <button class="btn btn-primary" type="submit">Update</button>
 
 
               </div>
 
 
            </form>
 
 
         </div>
 
 
         <div class="modal-footer">
 
 
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
 
 
         </div>
 
 
      </div>
 
 
   </div>
 
</div>
 
 
                    {% endfor %}
 
 
                </table>
 
 
            </div>
 
 
 
                  <!-- Modal Add Vehicle_Group-->
 
 
<div id="mymodal" class="modal fade" role="dialog">
   <div class="modal-dialog">
      <div class="modal-content">
         <div class="modal-header">
 
            <h4 class="modal-title">Add Vehicle</h4>
         </div>
         <div class="modal-body">
 
            <form action="{{url_for('views.insertgroup')}}" method="POST">
 
 
               <div class="form-group">
 
                  <label>Description:</label>
                  <input type="text" class="form-control" name="vehicle_groupdescription" required="1">
 
 
               </div>
 
 
               <div class="form-group">
 
 
                  
                
                  <label for="vehicle_groupstatus" class="form-label">Status:</label>
                  <select class="form-select" id="vehicle_groupstatus" name="vehicle_groupstatus" required="1">
                    <option>Active</option>
                    <option>Inactive</option>

                  </select>
 
 
               </div>
 
 
            
 
 
 
               <div class="form-group">
 
 
                  <button class="btn btn-primary" type="submit">Add Vehicle</button>
 
 
               </div>
 
 
            </form>
 
 
         </div>
 
 
         <div class="modal-footer">
 
 
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
 
 
         </div>
 
 
      </div>
 
 
   </div>
 
 
</div>
 
 
 
 
 
        </div>
 
    </div>
 
 
</div>


 
 
{% endblock %}

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
 